name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          cd "Machine Learning/GitHubActions"  # Navigate to your GitHubActions directory
          pip install -r src/requirements.txt  # Adjust if you have a requirements.txt

      - name: Run tests
        run: |
          cd "Machine Learning/GitHubActions"
          pytest tests/test_operations.py
