name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          cd "Machine Learning/GitHubActions"  # Navigate to your GitHubActions directory
          pip install -r src/requirements.txt  # Install dependencies

      - name: Run tests
        run: |
          cd "Machine Learning/GitHubActions"  # Ensure you're in the correct directory
          # Add the src directory to PYTHONPATH and run pytest
          PYTHONPATH=src pytest tests/test_operations.py
